name: Publish Docker image
on: [push]
jobs:
  push_to_registry:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Prep
        id: prep
        run: |
             branch=${GITHUB_REF##*/}
             sha=${GITHUB_SHA::8}
             ts=$(date +%s)
             echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: Checkout
        uses: actions/checkout@master
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ifmt/suap-os:latest,ifmt/suap-os:${{ steps.prep.outputs.BUILD_ID }}
